version: '3.2'

services:
  registry:
    container_name: "docker-registry"
    restart: unless-stopped
    image: registry:2
    ports:
      - 5000:5000
    environment:
      - REGISTRY_LOG_LEVEL=info
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/wsl.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/wsl.key
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - /opt/docker-registry/certs:/certs
      - /opt/docker-registry:/var/lib/registry
    extra_hosts:
      - "docker:192.168.37.2"
      - "wsl:192.168.37.2"
    #network_mode: host
    networks:
      - registry-network
  registry-ui:
    container_name: "docker-registry-ui"
    depends_on:
      - registry
    restart: unless-stopped
    image: parabuzzle/craneoperator:latest
    ports:
      - 8081:80
    environment:
      - REGISTRY_HOST=wsl
      - REGISTRY_PORT=5000
      - REGISTRY_PROTOCOL=https
      - SSL_VERIFY=false
      - ALLOW_REGISTRY_LOGIN=true
      - REGISTRY_ALLOW_DELETE=true
    extra_hosts:
      - "wsl:192.168.37.2"
    #network_mode: host
    networks:
      - registry-network
networks:
  registry-network:
    driver: bridge
