version: '3.2'

services:
  registry:
    container_name: "docker-registry"
    restart: unless-stopped
    image: registry:2
    ports:
      - 443:5000
    secrets:
    - wsl.crt.file
    - wsl.key.file
    environment:
      - REGISTRY_LOG_LEVEL=info
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      - REGISTRY_HTTP_TLS_CERTIFICATE=/run/secrets/wsl.crt.file
      - REGISTRY_HTTP_TLS_KEY=/run/secrets/wsl.key.file
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - /opt/docker-registry/config.yml:/etc/docker/registry/config.yml
      - /opt/docker-registry/registry:/var/lib/registry
    extra_hosts:
      - "docker:192.168.37.2"
      - "wsl:192.168.37.2"
    networks:
      - registry-network
  registry-ui:
    container_name: "docker-registry-ui"
    depends_on:
      - registry
    restart: unless-stopped
    image: parabuzzle/craneoperator:latest
    ports:
      - 8081:80
    environment:
      - REGISTRY_HOST=docker-registry
      - REGISTRY_PORT=5000
      - REGISTRY_PROTOCOL=https
      - SSL_VERIFY=false
      - ALLOW_REGISTRY_LOGIN=true
      - REGISTRY_ALLOW_DELETE=true
    extra_hosts:
      - "wsl:192.168.37.2"
    networks:
      - registry-network
networks:
  registry-network:
    driver: bridge
secrets:
  wsl.crt.file:
    file: /opt/docker-registry/certs/wsl.crt
  wsl.key.file:
    file: /opt/docker-registry/certs/wsl.key
